//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int notifId { get; set; }
        public int userId { get; set; }
        public string type { get; set; }
        public string notifcontent { get; set; }
        public System.DateTime date { get; set; }
        public int id { get; set; }
        public string status { get; set; }
    }
}
