//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasklog
    {
        public int tasklogId { get; set; }
        public int taskId { get; set; }
        public string logcontent { get; set; }
        public System.DateTime date { get; set; }
        public int assignto { get; set; }
    }
}
