//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int taskId { get; set; }
        public int projId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int createdby { get; set; }
        public int assignto { get; set; }
        public System.DateTime startdate { get; set; }
        public string enddate { get; set; }
        public string status { get; set; }
    }
}
